---
name: Authentication stage

description:
  Reusable test stage for authentication
stages:
  - id: login_get_token
    name: login

    request:
      url: "{url_endpoint}/auth"
      method: POST
      json:
        name: admin
        password: admin@123
      verify: false
    response:
      json:
        data:
          token: !anystr
          user:
            id: 1
            name: admin
      save:
        json:
          auth_token: data.token
